### ISSUE TITLE
Implement the domain model using Spring Data JPA

### ISSUE THREAD

**Issue by YoussefAgagg** [YoussefAgagg/article-webapp#1]
create classes for the domain objects in the ```domain``` package 
#### For entity `User`  :
* ManyToMany relationship:
`User` To `User` ->`followers`
User To User ->`following`
User to Authority ->`authorities`
* OneToMany relationship:
`User` To `Article` ->`articles`
#### For entity `Atricle`  :
* ManyToMany relationship:
`Atricle` To `Category`  ->`categories`
* OneToMany relationship
`Atricle` To `Comment` -> `comments`
#### For entity `Comment`  :
* ManyToOne relationship:
`Comment` To `User`  ->`user`

### class diagram 

![digrame](https://user-images.githubusercontent.com/62031222/174712806-aa361949-3954-4db6-b1cf-31847000f7e0.png)

**Comment by YoussefAgagg** [comment]
For `Article` entity  the field `content`  should be persisted as a large object to the database so use the  `@Lob` annotation

**Comment by YoussefAgagg** [comment]
add package `enumeration` under the `domin` package and put the enum `Gender` in it

**Comment by YoussefAgagg** [comment]
for entity `User`  mapping followers and following relationships  see this answer https://stackoverflow.com/a/13708470/11286441

**Comment by mohamedehab00** [comment]
> add package `enumeration` under the `domin` package and put the enum `Gender` in it

> DONE

**Comment by mohamedehab00** [comment]
> For `Article` entity the field `content` should be persisted as a large object to the database so use the `@Lob` annotation

> DONE
